# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := server test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

server: 
	@echo "==== Building server ($(config)) ===="
	@${MAKE} --no-print-directory -C server -f Makefile

test: 
	@echo "==== Building test ($(config)) ===="
	@${MAKE} --no-print-directory -C test -f Makefile

clean:
	@${MAKE} --no-print-directory -C server -f Makefile clean
	@${MAKE} --no-print-directory -C test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   server"
	@echo "   test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
